### PR TITLE
Istanbuljs upgrade and polymer 3 support

### LINKED ISSUE #7: include option is modified
The `include` option is modified. Why? One would assume that devs would set `include` and `exclude` globs to sufficiently limit files.

https://github.com/Bubbit/wct-istanbub/blob/master/lib/middleware.js#L105-L118

If I submitted a PR to change this, how would you prefer that it be handled? Remove the modifications or add an option to skip the modification?

### LINKED ISSUE #8: Shared NPM Notes
I'm working through getting the coverage running for an NPM build, and wanted to drop some of my notes as I work through various things in case anyone else runs into them.

1) It looks like the current approach to capturing the `absolutePath` is a little presumptive:
```
var absolutePath = req.url.replace(/^\/[^/]+\/[^/]+/, root);
``` 
If you're using a package name like `@org/package` there ends up being three levels of folder path to remove instead of two, so I think it might be better to use something like:
```
var re = new RegExp(`^\/[^/]+\/${basename.replace('/','\/')}`);
var absolutePath = req.url.replace(re, root);
```
2) I've just gotten this far and have to pivot to something else for a while, but once you're able to get files into the coverage checker I'm getting:
```
Failed to parse file: /Users/westbrook/Documents/web/repos/ll-footer/ll-footer.js
Error: Line 1: Unexpected token
    at ErrorHandler.constructError (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:5020:27)
    at Parser.unexpectedTokenError (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.tolerateUnexpectedToken (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:1998:42)
    at Parser.parseStatementListItem (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:3361:31)
    at Parser.parseFunctionSourceElements (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:4183:29)
    at Parser.parseFunctionExpression (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:4396:26)
    at Parser.parsePrimaryExpression (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:2373:38)
    at Parser.inheritCoverGrammar (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:2278:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/Users/westbrook/Documents/web/repos/ll-footer/node_modules/esprima/dist/esprima.js:2892:26)
```
Seems fairly likely that this is due to the `import {} from ...` statement, but I'll have to get into it later. First thought is either `esprima` isn't up-to-date on the `import` scene, being their last release was a year ago, or that the settings being pushed into it aren't.

More soon.

### LINKED ISSUE #10: Some files not included in code coverage
I have a file which is not being included in the coverage unless I include a `<link rel="">`. I'm using `"**/*.html"` in my includes list and have even tried including the file explicitly, but still it will not get covered since it doesn't contain a `<link rel="">`. Is this an issue or am I missing something?

### PR DESCRIPTION
**Pull request by Bubbit**
Closes #8, closes #7 and closes #10

### CODE REVIEW

File: lib/instrumenter.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+      return instrumenter.lastFileCoverage()
+    }
+  }
+}
+
+InstrumenterIstanbul.istanbul = () => {
+  return InstrumenterIstanbul._istanbul || (InstrumenterIstanbul._istanbul = require('istanbul-lib-instrument'))
+}
+
+module.exports = InstrumenterIstanbul
```
Comment (jimivdw) [inline lib/instrumenter.js]: No semi-colons?

Also, some of the functions could be shortened

File: lib/middleware.js [hunk 2]
```diff
@@ -1,137 +1,93 @@
...
+
+function instrumentFile(path, req, html) {
+  const asset = req.url;
 
-    function gotScript(code, loc) {
-      return instrumenter.instrumentSync(code, htmlFilePath);
+  if (fs.existsSync(path)) {
+    if (!cache[asset]) {
+      code = fs.readFileSync(path, 'utf8');
+      cache[asset] = html ? cache[asset] = scriptHook(code, { scriptCallback: instrumentScript }) : instrumenter.instrumentSync(code, path);
```
Comment (jimivdw) [inline lib/middleware.js]:
```
cache[asset] = html ? cache[asset] = scriptHook( ...
                      ~~~~~~~~~~~~~~~
```
Doesn't look quite right, or am I missing something here?

File: lib/middleware.js [hunk 3]
```diff
@@ -1,137 +1,93 @@
...
+    if (match(req.url, whitelist) && !match(req.url, blacklist)) {
       emitter.emit('log:debug', 'coverage', 'instrument', req.url);
 
-      if (absolutePath.match(/\.htm(l)?$/)) {
-        var html = instrumentHtml(absolutePath, req);
-        return res.send( html );
+      const re = new RegExp(`^\/[^/]+\/${basename.replace('/', '\/')}`);
+      const absolutePath = req.url.replace(re, root);
+
+      if (absolutePath.match(/\.js?$/)) {
```
Comment (jimivdw) [inline lib/middleware.js]: Is the `s` optional on purpose?

File: lib/middleware.js [hunk 4]
```diff
@@ -1,137 +1,93 @@
...
+        let html = instrumentFile(absolutePath, req);
+        res.type('application/javascript');
+        html = html.replace('coverage = global[gcv] || (global[gcv] = {});', 'coverage = global.WCT.share.__coverage__ || (global.WCT = { share: { __coverage__: {} } }); ');
+        return res.send(transform(req, html, basename, absolutePath, options.npm, root, emitter.options.clientOptions.root));
+      } else if (absolutePath.match(/\.htm(l)?$/)) {
+        let html = instrumentFile(absolutePath, req, true);
+        return res.send(html.replace('coverage = global[gcv] || (global[gcv] = {});', 'coverage = global.WCT.share.__coverage__ || (global.WCT = { share: { __coverage__: {} } }); '));
```
Comment (jimivdw) [inline lib/middleware.js]: Since it's here twice now, I would extract this replace thing.

Also, did you consider filing an issue with IstanbulJS for this?

File: lib/util.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+    return JSON.parse(config);
+  } catch (e) {
+    console.error(`Could not parse ${configPath} as JSON`);
+    console.error(e);
+  }
+  return null;
+}
+
+/**
+ * Taken from: https://github.com/Polymer/web-component-tester/blob/master/runner/config.ts
```
Comment (jimivdw) [inline lib/util.js]: Any reason not to simply import this file and use the function straight from wct?

File: lib/middleware.js (hunk 3 above)
Comment (jimivdw) [reply lib/middleware.js]: You could also consider adding the (less common) `.es` extension here

File: lib/middleware.js [hunk 6]
```diff
@@ -1,137 +1,93 @@
...
       }
 
-      return res.send( instrumentAsset(absolutePath, req) );
+      return next();
```
Comment (jimivdw) [inline lib/middleware.js]: Technically the instrument debug log is still emitted, even though the code has not been instrumented. Maybe make a distinction for that?

**Review by jimivdw — CHANGES_REQUESTED** [review]

File: lib/util.js (hunk 5 above)
Comment (Bubbit) [reply lib/util.js]: It was used somewhere else before as well, and it's a private function.

Now I have replaced it, it does increase the node_modules folder size purely for wct-istanbub a lot, but I guess considering you have web-component-tester anyway it shouldn't matter

File: lib/middleware.js (hunk 4 above)
Comment (Bubbit) [reply lib/middleware.js]: I did consider, but didn't do it yet

File: lib/util.js (hunk 5 above)
Comment (Bubbit) [reply lib/util.js]: On a second viewing, I did add the functionality of the root is not set to fallback to process.cwd() which web-component-tester has somewhere else in the chain. (which is why all the tests fail if I remove it ;))

**Review by jimivdw — APPROVED** [review]

**Comment by jimivdw** [comment]
lgtm
